# Enable mouse support
set -g mouse on

# Reload config file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# 256 color support
set -g default-terminal "screen-256color"

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Status Bar Configuration
set -g status on
set -g status-interval 1
set -g status-bg black
set -g status-fg white
set -g status-left-length 20
set -g status-right-length 140

