set number
set norelativenumber
set syntax=on

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent

set mouse=a
set clipboard=unnamed

set wildmenu
set incsearch
set hlsearch
set ignorecase
set smartcase

set backspace=indent,eol,start
set hidden
set scrolloff=3

set ruler
set showcmd
set nocursorline
set background=dark

nnoremap <Esc><Esc> :nohlsearch<CR>
